#index_content: "<h1>Hola desde {{ inventory_hostname }}</h1>"
index_content: "<h1>Hola desde {{ inventory_hostname }} ({{ ansible_default_ipv4.address }})</h1>"
index_path: "/var/www/html/index.html"
